### ISSUE TITLE
Tests sometimes fail with TypeError when creating observation object

### ISSUE THREAD

**Issue by aknierim** [radionets-project/pyvisgen#42]
The simulation unit tests in `tests/test_simulation.py` sometimes fail with

```
tests/test_simulation.py::test_vis_loop - TypeError: scalar 'Time' object is not iterable.
```

So somewhere the `Observation` class seems to try and iterate over a scalar, i.e. single value, `Time` object.

**Comment by Kevin2** [comment]
it is because our random seeds are not set correctly
sometimes the wrong seed leads to a observation config where the source is not visible

**Comment by aknierim** [comment]
Ah, that makes sense, thank you
